latchset/jose

Makefile.am, configure.ac, lib/openssl/lock.c
OpenSSL 1.0.2 requires thread locks to be thread safe. 1.1.0 creates thread locks automatically.
Signed-off-by: Christian Heimes <christian@python.org>
=> Init OpenSSL thread locks

cmd/jose.c
The jcmd_opt_set_jwkt() function calls json_loads() to decode the JSON
passed using the -i option. This function returns NULL on error and in
this case is attempted to first get the JSON from either the standard
input or a file.
But it's never checked again if one of those succeeded, so an invalid
JSON passed to jose jwk {gen,exc} leads to a NULL pointer dereference:
$ jose jwk gen -i '{"kty":"oct",,"bytes":32}' -o oct.jwk
Segmentation fault (core dumped)
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>
=> Fix NULL pointer dereference in jcmd_opt_set_jwkt()

doc/ronn/jose-alg.1, doc/ronn/jose-b64-dec.1, doc/ronn/jose-b64-enc.1, doc/ronn/jose-fmt.1, doc/ronn/jose-jwe-dec.1, doc/ronn/jose-jwe-enc.1, doc/ronn/jose-jwe-enc.1.html, doc/ronn/jose-jwe-enc.1.md, doc/ronn/jose-jwe-fmt.1, doc/ronn/jose-jwk-eql.1, doc/ronn/jose-jwk-exc.1, doc/ronn/jose-jwk-gen.1, doc/ronn/jose-jwk-pub.1, doc/ronn/jose-jwk-thp.1, doc/ronn/jose-jwk-use.1, doc/ronn/jose-jws-fmt.1, doc/ronn/jose-jws-sig.1, doc/ronn/jose-jws-ver.1, doc/ronn/jose.1
Do not escape single quotes, as they will appear as forward apostrophes
(0xc2b4) instead of ASCII ones (0x27) in the man pages.
This can be verified in a Fedora/RHEL system by running the following:
rpm -qla jose | grep '/man/' | xargs -n1 man -P cat | grep -e '`' -e '´'
The above command produces the following output on both Fedora with
jose-10-4.fc30.x86_64 and on RHEL8 with jose-10-2.el8.x86_64:
$ echo "$jwk" | jose fmt -j- -j ´"A128GCM"´ -s alg -Uo-
$ jose fmt -j ´{}´ -cs unprotected -q A128KW -s alg -UUo-
-p, `--password
$ jose jwk gen -i ´{"alg":"A128GCM"}´ -o key.jwk
$ jose jwe enc -i ´{"protected":{"zip":"DEF"}}´ ...
Encrypt with two keys and two passwords: $ jose jwk gen -i ´{"alg":"ECDH-ES+A128KW"}´ -o ec.jwk $ jose jwk gen -i ´{"alg":"RSA1_5"}´  -o  rsa.jwk  $
$ jose jwk gen -i …
=> José manpages have forward apostrophes instead of ASCII ones

tests/jose-b64-dec, tests/jose-b64-enc, tests/jose-fmt, tests/jose-jwe-dec, tests/jose-jwe-enc, tests/jose-jwe-fmt, tests/jose-jwk-exc, tests/jose-jwk-pub, tests/jose-jwk-thp, tests/jose-jwk-use, tests/jose-jws-fmt, tests/jose-jws-sig, tests/vectors/strip.sh
The previous commit (9e8c51b) changed the shell in the tests from bash
to sh and performed a few required conversions, however there were still
a few conversions to perform, most notably, using = instead of ==.
Tests were failing in Debian/Ubuntu.
=> Remove bashisms from tests

.github/workflows/build.yml, .github/workflows/install-dependencies, README.md
As travis as showing to be unreliable and slow, let's move the CI to
Github actions.
Note: I am not sure it supports ppc64le for now, so that wil not be
there as of now. Perhaps we can amend it in the future.
Note 2: ubuntu:bionic seems to have some issues with meson, so I left
it out also for now.
We are builing the following platforms for x86_64, with both clang and
gcc:
- fedora:rawhide
- fedora:latest
- centos:8
- debian:testing
- debian:latest
- ubuntu:devel
- ubuntu:rolling
- macos-latest
=> ci: add github actions

lib/openssl/compat.h, lib/openssl/rsa.c, tests/jose-jwk-gen, tests/meson.build
* ~~Upcoming OpenSSL version 3 has deprecated several low level functions, many of which we use with jose.
Since we also have `-Werror` turned on, the warnings generated by using these deprecated functions cause the build to fail, so let's make it so these specific warnings do not make the build fail, and we will be able to still build with OpenSSL 3 while a proper port to it happens in the meantime.~~
* declare OPENSSL_API_COMPAT 1.1.1, so that there will be no warnings/errors when building with OpenSSL 3,
due to the deprecated functions we currently use
* Minor fix in the meson file for the tests, prepending to the PATH variable, instead of appending, so that we make sure to use the utilities we have just built instead of ones that may exist in the system
* Updated our RSA code to apply …
=> Small changes to have jose build with openssl 3

doc/man/jose-jwe-enc.1.adoc
A new line is missing from jose man page.
adoc file will be changed to include it,
so that man page is more readable.
fix #78
=> Fix format of jose-jwe-enc man page

doc/doxygen/Doxyfile
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>
=> Avoid master word when possible

lib/hsh.c
The `hsh` local variable name conflicts with the function prototype of `hsh()` in `hsh.h`, causing the following build issues with old compilers (gcc 4.7):
```
hsh.c: In function 'hsh':
hsh.c:28:21: error: declaration of 'hsh' shadows a global declaration [-Werror=shadow]
hsh.c:26:1: error: shadowed declaration is here [-Werror=shadow]
hsh.c: In function 'hsh_buf':
hsh.c:60:21: error: declaration of 'hsh' shadows a global declaration [-Werror=shadow]
hsh.c:26:1: error: shadowed declaration is here [-Werror=shadow]
```
Therefore, we rename this local variable to `_hsh`.
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
[Fabrice: Resent PR as #51 was closed but meson doesn't fix this issue)]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> lib/hsh.c: rename hsh local variable

meson.build, meson_options.txt
Instead of always building man pages if asciidoc is installed, use a feature option to allow making its absence an error, or to avoid building it even if installed.
=> meson: add option to disable building manpages

lib/meson.build
The jose executable must link as a whole archive because of constructor usage.
=> jose: fix usage with static library

.github/workflows/build.yml, .github/workflows/install-dependencies
If I'm reading https://pagure.io/fedora-infrastructure/issue/11358 correctly there's hope that the docker build of Fedora Rawhide will be fixed in a couple of days.  Also if I'm reading that correctly, it seems like the docker build (which I'm assuming github CI uses) is not updated as frequently as you'd hope for a distribution that changes daily.  This change to quay.io for the rawhide builds seems to work for me and is an alternative to PR #133 that gets things working for the moment, and perhaps is a worthwhile longer term solution.
=> Alternative fix for fedora:rawide

tests/alg_comp.c
Different zlib implementations such as zlib-ng, QATzip and libnxz provide API and ABI compatibility with madler's zlib. However, they do not guarantee identical output.
This makes it very hard to compare the length or binary output of a compressed stream.
Instead of doing that, this patch aims to compare the input against the output of a compression and decompression cycle.
Fixes #142.
=> Adapt alg_comp test to different zlib (#142)

tests/alg_encr.c, tests/api_b64.c
=> Fix test compilation warnings

.github/workflows/build.yml, .github/workflows/install-dependencies, README.md
This updates github actions to:
Include current OS versions
Update actions/checkout to version 3 in advance of the imminent NodeJS deprecation
Add dependency installation for CentOS Stream versions
In my initial pass, there were failures for Ubuntu:bionic and, for clang on CentOS 7 and CentOS Stream 9. Rather than spend a lot of time trying to resolve the failures I simply removed the clang attempts for CentOS7 and Stream 9. It's probably some dependency issue if someone wants to chase it. I simply removed Ubuntu:bionic since it's EOL at the end of the month anyway.
=> Update CI (#8)

README.md, lib/openssl/ec.c, lib/openssl/ecdsa.c, lib/openssl/jwk.c, tests/jose-jwk-gen
Unfortunately it doesn't seem like RFC 8812 provides any "worked" examples, unlike some of the other RFCs. This roundtrips successfully with the implementation I recently added to github.com/lestrrat-go/jwx.
There's also a libsecp256k1 library from the bitcoin project (https://github.com/bitcoin-core/secp256k1). However it doesn't seem to have a stable release, and it's unclear that the extra dependency would be worth it over openssl for this usage.
If this is accepted, I'd be happy to add EdDSA and x25519/x448 curve support.
=> Add ES256K support

.github/workflows/build.yml
I don't know if this will help anyone else.  During all the pkg_config changes for PR #98 it was difficult to tell what effects changes where having. There doesn't seem to be a good way to "test" pkg_config as part of github actions (I think you'd have to install and then try and install something like tang on top of it.) But this tiny patch at least displays what pkg_config looks like so it's relatively easy to at least see what changed.
=> Display pkg_config in test logs

.github/workflows/build.yml
This does two straightforward things.  One, stop doing mass rebuilds when only the documentation has changed, and two update to actions/checkout@v4 in reaction to https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ which will obsolete actions/checkout@v3.  Unfortunately, the update to checkout (and thus node 20) seems to require libraries not available in CentOS 7.  I therefore marked it as unstable in the config to keep its failure from  stopping all other builds.  But I'm really not certain what is the best way to proceed.  It seems like checkout v3 will go end-of-life and not be usable "spring 2024" from the blog entry above.  CentOS 7 is scheduled to go end-of-life at the end of June.  So it seems like something will have to change before …
=> Build updates

lib/openssl/pbes2.c, tests/cve-2023-50967/cve-2023-50967.jwe, tests/cve-2023-50967/cve-2023-50967.jwk, tests/jose-jwe-dec, tests/meson.build
Unbounded p2c headers may be used to cause an application that accept PBES algorithms to spend a lot of resources running PBKDF2 with a very high number of iterations.
Limit the maximum number of iterations to to 32768.
Fixes: CVE-2023-50967
=> Fix potential DoS issue with p2c header

lib/jwe.c, lib/misc.c, lib/misc.h, lib/openssl/aescbch.c, lib/openssl/aesgcm.c, tests/alg_comp.c, tests/api_jwe.c, tests/jose-jwe-enc
When we have "zip" in the protected header, e.g.: "zip": "DEF", we should compress the payload before the encryption.
However, as it stands, we are doing the compression after the encryption, which results in the jose_jwe_enc* functions producing JWEs that we are unable to decrypt afterwards.
For the "zip" case, we do the compression now before the encryption, to fix this behavior.
Also add some tests to exercise these scenarios, both using the jose_jwe_enc*/jose_jwe_dec* functions, as well as the command line utilities jose jwe enc / jose jwe dec.
=> jwe: fix the case when we have "zip" in the protected header

cmd/jwk/thp.c, tests/jose-jwk-thp
`jose_jwk_thp_buf()` returns, on success, the number of bytes written; otherwise, it returns `SIZE_MAX`.
We now check its return properly, from `jcmd_jwk_thp()`, which is used by the CLI utility.
Fixes: #170
=> cmd/jwk: check return from jose_jwk_thp_buf() properly

.github/workflows/build.yml, .github/workflows/install-dependencies, .gitignore
Try fixing centos:stream based compilation by doing installation in the same step:
* The installation of yum-utils, epel-release, and common packages (${COMMON}) on CentOS Stream is now performed in a single dnf command. This helps dnf resolve all dependencies at once, preventing potential inconsistencies that can arise from multi-step installations.
* Updated CentOS Stream image: The CI workflow now uses quay.io/centos/centos:stream10 instead of the unstable stream10-development tag, ensuring a more stable and predictable build environment.
=> Fix centos:stream based compilation
